name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: "Test project"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x

      - name: Test (Debug)
        run: dotnet test -c Debug

      - name: Test (Release)
        run: dotnet test -c Release
